
import React from 'react';

export const TermsPage: React.FC = () => {

    const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
        <div>
            <h2 className="text-2xl font-bold text-white mb-4">{title}</h2>
            <div className="prose prose-invert prose-p:text-gray-300 prose-li:text-gray-300 prose-a:text-cyan-400 hover:prose-a:text-cyan-300 max-w-none space-y-4">
                {children}
            </div>
        </div>
    );

    return (
        <div className="bg-gray-900 py-20 sm:py-24">
            <div className="container mx-auto px-6">
                <div className="max-w-4xl mx-auto">
                    <div className="text-center mb-16">
                        <h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl">Terms of Service</h1>
                        <p className="mt-4 text-lg text-gray-400">
                            Last Updated: {new Date().toLocaleDateString()}
                        </p>
                    </div>

                    <div className="bg-gray-800/50 border border-gray-700 p-8 sm:p-12 rounded-2xl shadow-2xl space-y-12">
                        <Section title="1. Acceptance of Terms">
                            <p>
                                By accessing or using the Auto Doc application ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not use the Service. These Terms apply to all visitors, users, and others who access or use the Service.
                            </p>
                        </Section>

                        <Section title="2. Description of Service">
                            <p>
                                Auto Doc is an application that utilizes the Google Gemini AI to generate, analyze, rewrite, and customize documents based on user-provided prompts. The Service is provided by EDGTEC ("we", "us", "our").
                            </p>
                        </Section>

                        <Section title="3. User Accounts">
                            <p>
                                To access certain features of the Service, you may be required to create an account. You are responsible for safeguarding your account information and for any activities or actions under your account. You agree not to disclose your password to any third party and must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.
                            </p>
                        </Section>

                        <Section title="4. User Content and Conduct">
                            <p>
                                You are solely responsible for the content of your prompts and the documents generated ("User Content"). You agree not to use the Service to create any content that is unlawful, harmful, defamatory, obscene, or otherwise objectionable. We are not responsible for the accuracy, legality, or appropriateness of the content generated by the AI based on your prompts.
                            </p>
                            <p>
                                You retain all your rights to any User Content you submit, and you are responsible for protecting those rights.
                            </p>
                        </Section>

                        <Section title="5. Intellectual Property">
                            <p>
                                The Service and its original content (excluding User Content), features, and functionality are and will remain the exclusive property of EDGTEC and its licensors. The Service is protected by copyright, trademark, and other laws of both South Africa and foreign countries.
                            </p>
                        </Section>
                         
                        <Section title="6. Termination">
                            <p>
                                We may terminate or suspend your access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease.
                            </p>
                        </Section>

                        <Section title="7. Disclaimers and Limitation of Liability">
                            <p>
                                The Service is provided on an "AS IS" and "AS AVAILABLE" basis. While we strive to provide a high-quality service, we make no warranties of any kind, express or implied, that the content generated will be accurate, complete, reliable, or suitable for any particular purpose. Your use of the Service is at your sole risk.
                            </p>
                            <p>
                                In no event shall EDGTEC, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
                            </p>
                        </Section>
                        
                        <Section title="8. Governing Law">
                             <p>
                                These Terms shall be governed and construed in accordance with the laws of the Republic of South Africa, without regard to its conflict of law provisions.
                            </p>
                        </Section>
                        
                        <Section title="9. Changes to Terms">
                            <p>
                                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
                            </p>
                        </Section>
                        
                        <Section title="10. Contact Us">
                            <p>
                                If you have any questions about these Terms, please <a href="#!" onClick={(e) => e.preventDefault()}>contact us</a>.
                            </p>
                        </Section>
                    </div>
                </div>
            </div>
        </div>
    );
};
